---
version: "3.7"

# This Docker composition file is used to build and test the container

services:
  con-pca-tasks:
    # Run the container normally
    build:
      # VERSION must be specified on the command line:
      # e.g., --build-arg VERSION=0.0.1
      context: .
    container_name: con-pca-tasks
    image: cisagov/con-pca-tasks
    init: true
    restart: unless-stopped
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host

  con-pca-tasks-version:
    # Run the container to collect version information
    image: cisagov/con-pca-tasks
    init: true
    restart: "no"
    command: --version
